import './globals.css';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import { cn } from '@/lib/utils';
import LayoutHeader from '@/components/LayoutHeader';
import { ThemeProvider } from '@/components/ThemeProvider';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className='min-h-screen'>
      <body className={cn(inter.className,"flex flex-col min-h-[inherit] h-full bg-gradient-to-br dark:from-slate-950 dark:to-slate-800")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LayoutHeader/>
          {children}
          <Toaster position='top-right'/>
        </ThemeProvider>
      </body>
    </html>
  )
}
